name: AI Code Review with Claude

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  ai-code-review:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
          **/*.go
          **/*.mod
          **/*.sum
          **/*.md
          **/*.yml
          **/*.yaml
          **/*.json
        
    - name: Setup Go
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        
    - name: Run Go tests
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        go mod tidy
        go test ./... -v
        
    - name: Run Go vet
      if: steps.changed-files.outputs.any_changed == 'true'
      run: go vet ./...
      
    - name: Run golangci-lint
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        
    - name: Setup Node.js for review script
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install review script dependencies
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        cd .github/scripts
        npm install
        
    - name: Run AI Code Review
      if: steps.changed-files.outputs.any_changed == 'true'
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        cd .github/scripts
        node claude-review.js
